use explicit optionspec class
ionworks/iwutil pull request #3
Opened 2024-09-20 01:57 UTC by valentinsulzer

2024-09-20 19:38 UTC, kratman requested changes

2024-09-20 19:38 UTC, kratman commented on iwutil/__init__.py
> +            self.any_value_allowed = True
```suggestion
    def __init__(self, default_value, other_allowed_values: list | None =None):
        self.default_value = default_value
        self.allowed_values = None
        self.any_value_allowed = True
        if other_allowed_values is not None:
            self.allowed_values = [self.default_value]+other_allowed_values
            self.any_value_allowed = False
```

2024-09-20 19:38 UTC, kratman commented on iwutil/__init__.py
> +            self.any_value_allowed = True
This forces `other_allowed_values` to be a list and simplifies the code a bit

2024-09-21 05:08 UTC, kratman approved these changes

2024-09-21 05:08 UTC, merged

2024-09-21 05:09 UTC, valentinsulzer commented
@kratman working late!

2024-09-21 05:10 UTC, kratman commented
> @kratman working late!

Heard my phone beep and I knew it was an easy review to finish